# Generated by Django 4.1.2 on 2024-01-17 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('ML', 'Milk'), ('MS', 'MilkShake'), ('LS', 'Lassi'), ('IC', 'Ice-Cream')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Abia', 'Umuahia'), ('Adamawa', 'Yola'), ('Akwa-Ibom', 'Uyo'), ('Anambra', 'Awka'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Yenagoa'), ('Benue', 'Makurdi'), ('Borno', 'Maiduguri'), ('Cross-River', ' Calabar'), ('Delta', 'Asaba'), ('Ebonyi', 'Abakaliki'), ('Edo', 'Benin-City'), ('Ekiti', 'Ado-Ekiti'), ('Enugu', 'Enugu'), ('Gombe', 'Gombe'), ('Imo', 'Owerri'), ('Jigawa', 'Dutse'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Kastina', 'Kastina'), ('Kebbi', 'Birnin Kebbi'), ('Kogi', 'Lokoja'), ('Kwara', 'Ilorin'), ('Lagos', 'Ikeja'), ('Nassawara', 'Lafia'), ('Niger', 'Minna'), ('Ogun', 'Abeokuta'), ('Ondo', 'Akure'), ('Osun', 'Osogbo'), ('Oyo', 'Ibadan'), ('Plateau', 'Jos'), ('Rivers', 'Port-Harcourt'), ('Sokoto', 'Sokoto'), ('Taraba', 'Jalingo'), ('Yobe', 'Damaturu'), ('Zamafara', 'Gusau'), ('FCT', 'Abuja')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
