# Generated by Django 4.1.2 on 2026-04-24 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_flw_order_id_payment_tx_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Nigerian phone number (e.g., 08031234567 or +2348031234567).', regex='^(\\+234|0)[789][01]\\d{8}$')]),
        ),
    ]
